/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package parser.GUI;

import accesoDatos.ManejoBD;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputMethodEvent;
import java.awt.event.InputMethodListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.LinkedList;
import javax.swing.ComboBoxModel;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ListDataListener;
import javax.swing.table.AbstractTableModel;
import modelo.Dato;
import modelo.Funcion;

/**
 *
 * @author juan
 */
public class Funciones extends JInternalFrame{
    LinkedList <String[]> variables;
    LinkedList <String[]> variables_tabla;
    LinkedList<String> tipos_variables;
    LinkedList<Dato> variables_funciones;
    ManejoBD manejador=new ManejoBD();
            
    /**
     * Creates new form Funciones
     */
    public Funciones() {
        tipos_variables=manejador.getVariablesgroupedByType();
        tipos_variables.add(" ");
        variables_funciones=new LinkedList<Dato>();
        variables=manejador.getVariables(10);
        initComponents();
        this.functionsTbl.setModel(new modeloTabla());
        this.tipoVarCmb.setModel(new ComboModel());
        this.tipoVarCmb.addItemListener(new ComboEventsTop());
    
        
        this.btnDefinir.addActionListener(new EventHandler());
        this.btnEvaluar.addActionListener(new EventHandler());
        
        this.definirBtn.addActionListener(new EventHandler());
        this.textoVariable.addInputMethodListener(new InputMethodListener() {
            

            @Override
            public void inputMethodTextChanged(InputMethodEvent event) {
                JOptionPane.showMessageDialog(null,"cambio");
            }

            @Override
            public void caretPositionChanged(InputMethodEvent event) {
                JOptionPane.showMessageDialog(null,"cambio");
            }
        }); 
//        this.topNCB.addItemListener(new ComboEventsTop());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textoVariable = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        functionsTbl = new javax.swing.JTable();
        tipoVarCmb = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        definirBtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        functionArea = new javax.swing.JTextArea();
        functionNameTxt = new javax.swing.JTextField();
        argumentosTxt = new javax.swing.JTextField();
        valorRetorno = new javax.swing.JComboBox();
        sintaxisTxt = new javax.swing.JTextField();
        ayudaTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnEvaluar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        executionArea = new javax.swing.JTextArea();
        resultEval = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        definirPnl = new javax.swing.JPanel();
        txtDefinirVar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDefineExpression = new javax.swing.JTextArea();
        btnDefinir = new javax.swing.JButton();
        tipoVarCmb1 = new javax.swing.JComboBox();
        ayudaVar = new javax.swing.JTextField();
        presicionCmb = new javax.swing.JComboBox();
        ultimoNivelCk = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1000, 622));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Variables/Funciones"));

        functionsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Variables"
            }
        ));
        jScrollPane1.setViewportView(functionsTbl);

        tipoVarCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Entero", "String", "Booleano", "Fecha", " " }));
        tipoVarCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoVarCmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(textoVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tipoVarCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoVarCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Definición de funciones"));

        definirBtn.setText("Definir");

        functionArea.setColumns(20);
        functionArea.setRows(5);
        functionArea.setText("Expresión de la funcion");
        jScrollPane5.setViewportView(functionArea);

        functionNameTxt.setText("Nombre de la funcion");

        argumentosTxt.setText("Argumentos");

        valorRetorno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "number", "String", "Booleano" }));

        sintaxisTxt.setText("Sintaxis");

        ayudaTxt.setText("Ayuda");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(valorRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(functionNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(argumentosTxt))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sintaxisTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(definirBtn)
                    .addComponent(ayudaTxt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(functionNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(argumentosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(ayudaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sintaxisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(definirBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Evaluar"));

        btnEvaluar.setText("Evaluar");

        executionArea.setColumns(20);
        executionArea.setRows(5);
        executionArea.setText("Expresión a evaluar");
        jScrollPane3.setViewportView(executionArea);

        resultEval.setText("Resultado");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEvaluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultEval, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnEvaluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resultEval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan\\Pictures\\coomeva.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        definirPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Definicion  Variables"));

        txtDefinirVar.setText("Nombre");

        txtDefineExpression.setColumns(20);
        txtDefineExpression.setRows(5);
        txtDefineExpression.setText("Expresión");
        jScrollPane2.setViewportView(txtDefineExpression);

        btnDefinir.setText("Definir");

        tipoVarCmb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Booleano", "Entero", "String", "Flotante" }));

        ayudaVar.setText("Ayuda");

        presicionCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6" }));
        presicionCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presicionCmbActionPerformed(evt);
            }
        });

        ultimoNivelCk.setText("Ultimo Nivel");
        ultimoNivelCk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimoNivelCkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout definirPnlLayout = new javax.swing.GroupLayout(definirPnl);
        definirPnl.setLayout(definirPnlLayout);
        definirPnlLayout.setHorizontalGroup(
            definirPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(definirPnlLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtDefinirVar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tipoVarCmb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(presicionCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnDefinir)
                .addGap(18, 18, 18)
                .addComponent(ultimoNivelCk)
                .addGap(18, 18, 18)
                .addComponent(ayudaVar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        definirPnlLayout.setVerticalGroup(
            definirPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(definirPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(definirPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDefinirVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoVarCmb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(presicionCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ultimoNivelCk)
                    .addComponent(btnDefinir)
                    .addComponent(ayudaVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(definirPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(definirPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoVarCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoVarCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoVarCmbActionPerformed

    private void presicionCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presicionCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_presicionCmbActionPerformed

    private void ultimoNivelCkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimoNivelCkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ultimoNivelCkActionPerformed

  
        public class modeloTabla extends AbstractTableModel{
        
        public int getColumnCount(){
            return variables.getFirst().length;
        }  
        
        public String getColumnName(int indice){
            if(indice==0)
            {
                return "Nombre";
            }else if(indice==1)
            {
                return "Expresion";
            }else
            {
                return "Tipo";
            }
        }

        @Override
        public int getRowCount() {
            return variables.size();
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            String[] actualVariables=variables.get(rowIndex);
            return actualVariables[columnIndex];
        }
    }
        
      public class ComboModel implements ComboBoxModel{
        Object selected;
        @Override
        public void setSelectedItem(Object anItem) {
            this.selected=anItem;
        }

        @Override
        public Object getSelectedItem() {
            return selected;
        }

        @Override
        public int getSize() {
            return tipos_variables.size();
        }

        @Override
        public Object getElementAt(int index) {
            return tipos_variables.get(index);
        }

        @Override
        public void addListDataListener(ListDataListener l) {
        }

        @Override
        public void removeListDataListener(ListDataListener l) {
        }
    
    }
  
public class EventHandler implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) 
        {
            if(e.getSource()==btnDefinir)
            {
                String tipo=(String)tipoVarCmb.getItemAt(tipoVarCmb.getSelectedIndex());
                String precision=(String)presicionCmb.getItemAt(presicionCmb.getSelectedIndex());
                int predecesor=0;
                boolean ultimo_nivel=ultimoNivelCk.isSelected();
                if(!ultimo_nivel)
                {
                    predecesor=1;
                }
                String nombre=txtDefineExpression.getText();
                String expression=txtDefinirVar.getText();
                String ayuda = ayudaVar.getText();
                String[]variable={nombre,expression,ayuda,tipo,""+predecesor+"",precision};
                ManejoBD b =new ManejoBD();
                b.insertarVariableBD(variable);
                System.out.println("tipo->"+tipo+" nombre->"+nombre+" expresion->"+expression);
            }            
            if(e.getSource()==btnEvaluar)
            {
                ManejoBD b =new ManejoBD();
                String contenido= executionArea.getText();
                //b.runEval("(3*A) * (2*B - 2*D)*3+F");
                resultEval.setText(b.runEval(contenido));

            }
            if(e.getSource()==definirBtn)
            {
                String nombreFuncion=functionNameTxt.getText();
                String contenidoArea=functionArea.getText();
                String argumentos =argumentosTxt.getText();
                String ayuda=ayudaTxt.getText();
                String sintaxis=sintaxisTxt.getText();
                String[] argumentosArray =argumentos.split(",");
                String tipo_retorno=(String)valorRetorno.getSelectedItem();
                for(int i=0;i<argumentosArray.length;i++)
                {   String[]tmp=argumentosArray[i].split(" ");
                    Dato dato=new Dato( );
                    dato.setNombre(tmp[0]);
                    dato.setTipo(tmp[1]);
                    variables_funciones.add(dato);
                    System.out.println("nommbre=>"+tmp[0]+"  nombre=>"+tmp[1]);
                }
                ManejoBD b =new ManejoBD();
                Funcion funcion=new Funcion(nombreFuncion, sintaxis, ayuda, contenidoArea, tipo_retorno, variables_funciones) ;
                b.crearFuncion(funcion);
                //System.out.println("tamaños "+variables_funciones.size());
               String[] respuesta =contenidoArea.split("return");
               //   b.insertarVariableBD(variable);
  //              System.out.println("tipo->"+tipo+" nombre->"+nombre+" expresion->"+expression);
            }
            if(e.getSource()==btnEvaluar)
            {
             
            }
        }
    }

    public class ComboEventsTop implements ItemListener{

        public void itemStateChanged(ItemEvent e) {
            String value=((String)tipoVarCmb.getSelectedItem());
            ModifiedTableModel newModel=new ModifiedTableModel(value);
            functionsTbl.setModel(newModel);
            newModel.fireTableDataChanged();
           
        }
    }
public class ModifiedTableModel extends AbstractTableModel{
      ManejoBD b=new ManejoBD();
        public ModifiedTableModel(String value) 
        {
            variables_tabla=b.getVariablesByType(value);
        }
        
        public int getColumnCount(){
            return variables_tabla.getFirst().length;
        }  
        
        public String getColumnName(int indice){
            if(indice==0)
            {
                return "Nombre";
            }else if(indice==1)
            {
                return "Expresion";
            }else
            {
                return "Tipo";
            }
                }

        @Override
        public int getRowCount() {
            return variables_tabla.size();
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            String[] actualOrganism=variables_tabla.get(rowIndex);
            return actualOrganism[columnIndex];
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField argumentosTxt;
    private javax.swing.JTextField ayudaTxt;
    private javax.swing.JTextField ayudaVar;
    private javax.swing.JButton btnDefinir;
    private javax.swing.JButton btnEvaluar;
    private javax.swing.JButton definirBtn;
    private javax.swing.JPanel definirPnl;
    private javax.swing.JTextArea executionArea;
    private javax.swing.JTextArea functionArea;
    private javax.swing.JTextField functionNameTxt;
    private javax.swing.JTable functionsTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JComboBox presicionCmb;
    private javax.swing.JTextField resultEval;
    private javax.swing.JTextField sintaxisTxt;
    private javax.swing.JTextField textoVariable;
    private javax.swing.JComboBox tipoVarCmb;
    private javax.swing.JComboBox tipoVarCmb1;
    private javax.swing.JTextArea txtDefineExpression;
    private javax.swing.JTextField txtDefinirVar;
    private javax.swing.JCheckBox ultimoNivelCk;
    private javax.swing.JComboBox valorRetorno;
    // End of variables declaration//GEN-END:variables
}
