
package parser.GUI;

import accesoDatos.ManejoBD;
import accesoDatos.accesoDatos;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.StringReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

public class GUI extends JInternalFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.btnDefinir.addActionListener(new EventHandler());
        this.btnEvaluar.addActionListener(new EventHandler());
         setBackground(new java.awt.Color(255, 255, 255));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btnEvaluar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        executionArea = new javax.swing.JTextArea();
        resultEval = new javax.swing.JTextField();
        definirPnl = new javax.swing.JPanel();
        txtDefinirVar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDefineExpression = new javax.swing.JTextArea();
        btnDefinir = new javax.swing.JButton();
        tipoVarCmb = new javax.swing.JComboBox();
        ayudaVar = new javax.swing.JTextField();
        presicionCmb = new javax.swing.JComboBox();
        ultimoNivelCk = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Variables");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Expresion"));

        btnEvaluar.setText("Evaluar");

        executionArea.setColumns(20);
        executionArea.setRows(5);
        executionArea.setText("Expresión");
        jScrollPane3.setViewportView(executionArea);

        resultEval.setText("Resultado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEvaluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultEval))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnEvaluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resultEval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        definirPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Definicion  Variables"));

        txtDefinirVar.setText("Nombre");

        txtDefineExpression.setColumns(20);
        txtDefineExpression.setRows(5);
        txtDefineExpression.setText("Expresión");
        jScrollPane2.setViewportView(txtDefineExpression);

        btnDefinir.setText("Definir");

        tipoVarCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Booleano", "Entero", "String", "Flotante" }));

        ayudaVar.setText("Ayuda");

        presicionCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6" }));
        presicionCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presicionCmbActionPerformed(evt);
            }
        });

        ultimoNivelCk.setText("Ultimo Nivel");
        ultimoNivelCk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimoNivelCkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout definirPnlLayout = new javax.swing.GroupLayout(definirPnl);
        definirPnl.setLayout(definirPnlLayout);
        definirPnlLayout.setHorizontalGroup(
            definirPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(definirPnlLayout.createSequentialGroup()
                .addGroup(definirPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(definirPnlLayout.createSequentialGroup()
                        .addGroup(definirPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(definirPnlLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(definirPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tipoVarCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDefinirVar)
                                    .addComponent(presicionCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(definirPnlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ultimoNivelCk))
                            .addGroup(definirPnlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnDefinir)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(definirPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ayudaVar, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        definirPnlLayout.setVerticalGroup(
            definirPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(definirPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(definirPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(definirPnlLayout.createSequentialGroup()
                        .addComponent(txtDefinirVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(tipoVarCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(presicionCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(ultimoNivelCk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDefinir))
                    .addComponent(jScrollPane2))
                .addGap(9, 9, 9)
                .addComponent(ayudaVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan\\Pictures\\coomeva.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(definirPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(definirPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void presicionCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presicionCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_presicionCmbActionPerformed

    private void ultimoNivelCkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimoNivelCkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ultimoNivelCkActionPerformed

    /**
     * @param args the command line arguments
     */
    
     public class EventHandler implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) 
        {
            if(e.getSource()==btnEvaluar)
            {
                ManejoBD b =new ManejoBD();
                String contenido= executionArea.getText();
                //b.runEval("(3*A) * (2*B - 2*D)*3+F");
               resultEval.setText(b.runEval(contenido));
            }
            if(e.getSource()==btnDefinir)
            {
                String tipo=(String)tipoVarCmb.getItemAt(tipoVarCmb.getSelectedIndex());
                String precision=(String)presicionCmb.getItemAt(presicionCmb.getSelectedIndex());
                int predecesor=0;
                boolean ultimo_nivel=ultimoNivelCk.isSelected();
                if(!ultimo_nivel)
                {
                    predecesor=1;
                }
                String nombre=txtDefineExpression.getText();
                String expression=txtDefinirVar.getText();
                String ayuda = ayudaVar.getText();
                String[]variable={nombre,expression,ayuda,tipo,""+predecesor+"",precision};
                ManejoBD b =new ManejoBD();
                b.insertarVariableBD(variable);
                System.out.println("tipo->"+tipo+" nombre->"+nombre+" expresion->"+expression);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ayudaVar;
    private javax.swing.JButton btnDefinir;
    private javax.swing.JButton btnEvaluar;
    private javax.swing.JPanel definirPnl;
    private javax.swing.JTextArea executionArea;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox presicionCmb;
    private javax.swing.JTextField resultEval;
    private javax.swing.JComboBox tipoVarCmb;
    private javax.swing.JTextArea txtDefineExpression;
    private javax.swing.JTextField txtDefinirVar;
    private javax.swing.JCheckBox ultimoNivelCk;
    // End of variables declaration//GEN-END:variables
}
